// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth.index'
import { Route as AuthHistoryImport } from './routes/_auth.history'
import { Route as AuthAlertsImport } from './routes/_auth.alerts'
import { Route as AuthTransferOrderIdImport } from './routes/_auth.transfer.$orderId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthHistoryRoute = AuthHistoryImport.update({
  path: '/history',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAlertsRoute = AuthAlertsImport.update({
  path: '/alerts',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTransferOrderIdRoute = AuthTransferOrderIdImport.update({
  path: '/transfer/$orderId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/alerts': {
      preLoaderRoute: typeof AuthAlertsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/history': {
      preLoaderRoute: typeof AuthHistoryImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/transfer/$orderId': {
      preLoaderRoute: typeof AuthTransferOrderIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthAlertsRoute,
    AuthHistoryRoute,
    AuthIndexRoute,
    AuthTransferOrderIdRoute,
  ]),
  LoginRoute,
])
